"use client";
import { FormEvent, useState } from "react";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { addDoc, collection } from "firebase/firestore";
import { firestore } from "../../lib/firebase";

const initial = { name: "", email: "", phone: "", company: "", origin: "", destination: "", service: "GCC road freight", weight: "", details: "" };
export function QuoteForm() {
  const [form, setForm] = useState(initial); const [state, setState] = useState<"idle" | "sending" | "success" | "error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); setState("sending"); setMessage(""); try { await addDoc(collection(firestore, "quoteRequests"), { ...form, status: "New", createdAt: new Date().toISOString() }); setState("success"); setForm(initial); } catch (error) { setState("error"); setMessage(error instanceof Error ? error.message : "Unable to send request"); } }
  if (state === "success") return <div className="quote-success"><CheckCircle2 size={47} /><h2>Request received.</h2><p>Thank you. A RedLine freight specialist will contact you shortly with the next steps.</p><button onClick={() => setState("idle")}>Send another request</button></div>;
  return <form className="quote-form" onSubmit={submit}><div className="quote-form-head"><span>SHIPMENT REQUEST</span><h2>Get your RedLine quote</h2></div><div className="quote-form-grid"><label>Full name *<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Business email *<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label>Phone number<input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="+965" /></label><label>Company<input value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} /></label><label>Origin *<input required value={form.origin} onChange={(e) => setForm({ ...form, origin: e.target.value })} placeholder="City, country" /></label><label>Destination *<input required value={form.destination} onChange={(e) => setForm({ ...form, destination: e.target.value })} placeholder="City, country" /></label><label>Service *<select value={form.service} onChange={(e) => setForm({ ...form, service: e.target.value })}><option>GCC road freight</option><option>Air freight</option><option>Ocean freight</option><option>Kuwait distribution</option><option>Warehousing</option><option>Project cargo</option></select></label><label>Estimated weight<input value={form.weight} onChange={(e) => setForm({ ...form, weight: e.target.value })} placeholder="e.g. 850 kg" /></label><label className="quote-full">Cargo details<textarea rows={4} value={form.details} onChange={(e) => setForm({ ...form, details: e.target.value })} placeholder="Cargo type, dimensions, number of pieces and any special handling needs" /></label></div>{state === "error" && <p className="form-error">{message}</p>}<button className="quote-submit" disabled={state === "sending"}>{state === "sending" ? "Sending request…" : <>Request my quote <ArrowRight size={17} /></>}</button><small className="form-privacy">Your information is used only to prepare and follow up on this freight request.</small></form>;
}
